### ISSUE TITLE
How to not include CDN jquery in the production bundle?

### ISSUE THREAD

**Issue by duongphuhiep** [stealjs/quick-start#2]
I wish to load jquery from CDN and not include it in the bundle. Is it possible? and how?

```
System.config({
  "main": "main",
  "paths": {
    "jquery": "https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js",
  }
})
```

![image](https://cloud.githubusercontent.com/assets/1638594/9241358/c5467ed0-4172-11e5-8a9d-5f9aef87b33f.png)

**Comment by pYr0x** [comment]
please look on this guide http://stealjs.com/docs/StealJS.loading-from-cdn.html
